### ISSUE TITLE
关于控制台打印的框架信息不存在

### ISSUE THREAD

**Issue by XueHuaiHxh** [chuzhixin/vue-admin-beautiful-template#3]
控制台没有打印框架信息呀,然后大佬的代码里说保留作者信息可商用
然后在home那个页面说保留框架打印信息可商用,但原本代码里就没有打印

**Comment by chuzhixin** [comment]
![image](https://user-images.githubusercontent.com/26647258/86334887-58ceb900-bc80-11ea-9722-6fb00c708202.png)
![image](https://user-images.githubusercontent.com/26647258/86334952-6c7a1f80-bc80-11ea-941c-05110c62a4e1.png)
控制台的打印打包后会显示，开源版不可以去除
页面上的版权信息，无论你是否是授权用户，都有配置不显示的权利，无需付费也可以配置关闭，建议保留代码作者的信息，用于框架宣传

**Comment by XueHuaiHxh** [comment]
哦哦哦  ,好的 ,谢谢大佬 ,主要是开发环境的时候 没注意到.
